version: '3.6'
#ddev-generated
services:

  db:
    container_name: ddev-${DDEV_SITENAME}-db
    build:
      context: '/Users/jroulin/Dev/covid19_pocus_ultrasound/.ddev/db-build'
      dockerfile: '/Users/jroulin/Dev/covid19_pocus_ultrasound/.ddev/.dbimageBuild/Dockerfile'
      args:
        BASE_IMAGE: $DDEV_DBIMAGE
        username: 'jroulin'
        uid: '501'
        gid: '20'
    image: ${DDEV_DBIMAGE}-${DDEV_SITENAME}-built
    stop_grace_period: 60s
    volumes:
      - type: "volume"
        source: mariadb-database
        target: "/var/lib/mysql"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
      - ddev-global-cache:/mnt/ddev-global-cache
    restart: "no"
    user: "$DDEV_UID:$DDEV_GID"
    hostname: covidscreen-db
    ports:
      - "127.0.0.1:$DDEV_HOST_DB_PORT:3306"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: php
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - COLUMNS=$COLUMNS
      - LINES=$LINES
      - TZ=
      - DDEV_PROJECT=covidscreen
    command: "$DDEV_MARIADB_LOCAL_COMMAND"
    healthcheck:
      interval: 1s
      retries: 30
      start_period: 20s
      timeout: 120s

  web:
    container_name: ddev-${DDEV_SITENAME}-web
    build:
      context: '/Users/jroulin/Dev/covid19_pocus_ultrasound/.ddev/web-build'
      dockerfile: '/Users/jroulin/Dev/covid19_pocus_ultrasound/.ddev/.webimageBuild/Dockerfile'
      args:
        BASE_IMAGE: $DDEV_WEBIMAGE
        username: 'jroulin'
        uid: '501'
        gid: '20'
    image: ${DDEV_WEBIMAGE}-${DDEV_SITENAME}-built
    cap_add:
      - SYS_PTRACE
    volumes:
      
      - type: bind
        source: ../
        target: /var/www/html
        
        consistency: cached
        
      
      - ".:/mnt/ddev_config:ro"
      - ddev-global-cache:/mnt/ddev-global-cache
      
      - ddev-ssh-agent_socket_dir:/home/.ssh-agent
      

    restart: "no"
    user: "$DDEV_UID:$DDEV_GID"
    hostname: covidscreen-web
    
    links:
      - db:db
    
    # ports is list of exposed *container* ports
    ports:
      - "127.0.0.1:$DDEV_HOST_WEBSERVER_PORT:80"
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:443"
    environment:
      - DOCROOT=$DDEV_DOCROOT
      - DDEV_PHP_VERSION=$DDEV_PHP_VERSION
      - DDEV_WEBSERVER_TYPE=$DDEV_WEBSERVER_TYPE
      - DDEV_PROJECT_TYPE=$DDEV_PROJECT_TYPE
      - DDEV_ROUTER_HTTP_PORT=$DDEV_ROUTER_HTTP_PORT
      - DDEV_ROUTER_HTTPS_PORT=$DDEV_ROUTER_HTTPS_PORT
      - DDEV_XDEBUG_ENABLED=$DDEV_XDEBUG_ENABLED
      - IS_DDEV_PROJECT=true
      - DOCKER_IP=127.0.0.1
      - HOST_DOCKER_INTERNAL_IP=
      - DEPLOY_NAME=local
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - COLUMNS=$COLUMNS
      - LINES=$LINES
      - TZ=
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      # To expose a container port to a different host port, define the port as hostPort:containerPort
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025
      # You can optionally expose an HTTPS port option for any ports defined in HTTP_EXPOSE.
      # To expose an HTTPS port, define the port as securePort:containerPort.
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025
      - SSH_AUTH_SOCK=/home/.ssh-agent/socket
      - DDEV_PROJECT=covidscreen
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: php
      com.ddev.approot: $DDEV_APPROOT

    external_links:
    - "ddev-router:covidscreen.ddev.site"
    
    healthcheck:
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 120s


  dba:
    container_name: ddev-${DDEV_SITENAME}-dba
    image: $DDEV_DBAIMAGE
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: php
      com.ddev.approot: $DDEV_APPROOT
    links:
      - db:db
    ports:
      - "80"
    hostname: covidscreen-dba
    environment:
      - PMA_USER=db
      - PMA_PASSWORD=db
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - TZ=
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      - HTTP_EXPOSE=${DDEV_PHPMYADMIN_PORT}:8036
      - HTTPS_EXPOSE=${DDEV_PHPMYADMIN_HTTPS_PORT}:8036
    healthcheck:
      interval: 120s
      timeout: 2s
      retries: 1

networks:
  default:
    external:
      name: ddev_default
volumes:
  
  mariadb-database:
    name: "${DDEV_SITENAME}-mariadb"
  
  
  ddev-ssh-agent_socket_dir:
    external: true
  
  ddev-global-cache:
    name: ddev-global-cache

  

  